### ISSUE TITLE
던전 스크립트 관련 변수 이름이 통일되었으면 좋겠어요

### ISSUE THREAD

**Issue by ninthsun91** [Hanghae-GREATGREAT/Dev#43]
[main.js](https://github.com/Hanghae-GREATGREAT/Dev/blob/5b2948755b8c8775a3c6c1bc5d2e3b1fe24b850c/src/views/public/js/main.js#L106)
[battle.service.ts](https://github.com/Hanghae-GREATGREAT/Dev/blob/5b2948755b8c8775a3c6c1bc5d2e3b1fe24b850c/src/battle/battle.service.ts#L33)

던전 스크립트 관련 변수 이름이 서로 다른데 같으면 좋을 것 같아요.
같게 만들고 나서 아래 같은 부분 구조분해할당으로 바꿔주세요.
```
        const name = data.dungeonName;
        const op = data.opsions;
        const lev = data.recommendLevel;
        const script = data.script;
```

**Comment by JangKroed** [comment]
네 일단 장비랑 몬스터, 스킬 구성후 배틀 쪽 수정 완료되거나 진행중에 상의하고 맞추도록 하겠습니다 !

**Comment by Monggle88** [comment]
오늘 밤 회의전까지 한번 굴러가도록 해보겠습니다 !
